filenames_to_auto_rename:
  - diffusion_pytorch_model
  - lora
  - checkpoint
  - ckpt
  - model
  - ae

model_base_names:
  flux1:
    - flux
    - flux-1
    - flux_1
    - flux.1 dev
    - flux.1 d
  sdxl:
    - SD XL
    - sd xl 
    - SDXL 1.0
    - sd-xl
    - sd_xl
    - stable-diffusion-xl
    - stablediffusionxl
  sd15:
    - sd-15
    - sd_15
    - stable-diffusion-1.5
    - stablediffusion15
  pony:
    - PONY

model_type_names:
  loras:
    - lora
    - loras
    - loramodel
    - loramodels
  checkpoints:
    - checkpoint
    - checkpoints
    - ckpt
    - ckpts
    - model
    - models
  controlnet:
    - controlnet
    - control
    - cn
  vae:
    - vae
    - autoencoder
    - ae
  unet:
    - unet
    - u-net
  textualinversion:
    - textualinversion
    - embedding
    - embeddings
  hypernetwork:
    - hypernetwork
    - hypernet
    - hyper
  upscaler:
    - upscaler
    - upscale
    - upscaling